
const Q=window.PP_DATA.questions,TOP=[...new Set(Q.map(x=>x.topic))],KEY='princeprep_v2_full';let S=load(),SES=null,TICK=null,FC=[],FI=0,FLIP=false;
function blank(){return{answered:0,correct:0,topics:{},wrong:{},mocks:[],examDate:'',study:[],seen:{},flash:{}}}function load(){try{return Object.assign(blank(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return blank()}}function save(){localStorage.setItem(KEY,JSON.stringify(S))}function sh(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function st(t){return S.topics[t]||{a:0,c:0}}function mas(t){let x=st(t);return x.a?Math.round(100*x.c/x.a):0}function pc(a,b){return b?Math.round(100*a/b):0}
function readiness(){if(!S.answered)return 0;let a=pc(S.correct,S.answered),b=100*TOP.filter(t=>st(t).a>=4).length/TOP.length,m=S.mocks.length?S.mocks.slice(-3).reduce((x,y)=>x+y.score,0)/Math.min(3,S.mocks.length):a;return Math.round(a*.4+b*.2+m*.4)}function mark(){let d=new Date().toISOString().slice(0,10);if(!S.study.includes(d)){S.study.push(d);save()}}function streakN(){let n=0,d=new Date();while(S.study.includes(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='home')home();if(id==='learn')learn();if(id==='progress')progress();if(id==='settings')examdate.value=S.examDate||'';scrollTo(0,0)}
function home(){ready.textContent=readiness()+'%';answered.textContent=S.answered;accuracy.textContent=S.answered?pc(S.correct,S.answered)+'%':'—';bestmock.textContent=S.mocks.length?Math.max(...S.mocks.map(x=>x.score))+'%':'—';streak.textContent='🔥 '+streakN();wrongcount.textContent=Object.keys(S.wrong).length+' mistakes';mission.textContent=S.answered?'Strengthen weak areas':'Build your baseline';countText();let w=[...TOP].sort((a,b)=>(st(a).a?mas(a):-1)-(st(b).a?mas(b):-1)).slice(0,5);weak.innerHTML=w.map(t=>`<div class="weakrow"><div class="row"><b>${t}</b><span>${st(t).a?mas(t)+'%':'Not tested'}</span></div><div class="bar"><i style="width:${mas(t)}%"></i></div></div>`).join('')}
function countText(){if(!S.examDate){countdown.textContent='Set your exam date';countsub.textContent='Your revision plan will adapt as the date approaches.';return}let n=new Date();n.setHours(0,0,0,0);let e=new Date(S.examDate+'T00:00:00'),d=Math.ceil((e-n)/86400000);countdown.textContent=d>=0?`${d} day${d===1?'':'s'} to exam`:'Exam date passed';countsub.textContent=d>10?'Build breadth and accuracy.':d>3?'Prioritize Rescue Mode and full mocks.':'Final review: weak areas, recall and exam technique.'}
function pool(n,filter=null,weighted=false){let p=filter?Q.filter(filter):Q;if(weighted){let w=[...TOP].sort((a,b)=>mas(a)-mas(b)).slice(0,4),prio=p.filter(q=>w.includes(q.topic));p=[...prio,...prio,...p]}let u=p.filter(q=>!S.seen[q.id]);return sh(u.length>=n?u:p).slice(0,n)}
function startAdaptive(n){start('Adaptive Practice',pool(n,null,true),false)}function startRescue(){let w=[...TOP].sort((a,b)=>(st(a).a?mas(a):-1)-(st(b).a?mas(b):-1)).slice(0,3);start('Rescue Mode',pool(15,q=>w.includes(q.topic),true),false)}function startTopic(t){start(t+' Focus',pool(12,q=>q.topic===t),false)}function startMock(){start('Foundation Mock',pool(60),true)}
function start(title,items,mock){clearInterval(TICK);SES={title,items,i:0,c:0,mock,done:false,left:mock?3600:null};qmode.textContent=mock?'TIMED MOCK':'PRACTICE';qtitle.textContent=title;show('quiz');if(mock){timer.textContent='60:00';TICK=setInterval(()=>{SES.left--;let m=Math.floor(SES.left/60),s=SES.left%60;timer.textContent=`${m}:${String(s).padStart(2,'0')}`;if(SES.left<=0){clearInterval(TICK);finish()}},1000)}else timer.textContent='';renderQ()}
function renderQ(){let q=SES.items[SES.i];quizbox.innerHTML=`<div class="qprogress"><i style="width:${100*SES.i/SES.items.length}%"></i></div><div class="qcard"><div class="qmeta">${q.topic.toUpperCase()} · ${SES.i+1}/${SES.items.length}</div><h3>${q.question}</h3><div class="options">${q.options.map((o,i)=>`<button class="option" onclick="answer(${i})">${o}</button>`).join('')}</div><div id="feedback"></div></div>`}
function answer(i){if(SES.done)return;SES.done=true;let q=SES.items[SES.i],sel=q.options[i],ok=sel===q.answer;S.answered++;if(ok){S.correct++;SES.c++}S.topics[q.topic]=S.topics[q.topic]||{a:0,c:0};S.topics[q.topic].a++;if(ok)S.topics[q.topic].c++;S.seen[q.id]=(S.seen[q.id]||0)+1;if(ok)delete S.wrong[q.id];else S.wrong[q.id]={id:q.id,question:q.question,answer:q.answer,selected:sel,topic:q.topic,explanation:q.explanation};save();mark();document.querySelectorAll('.option').forEach((b,j)=>{if(b.textContent===q.answer)b.classList.add('good');if(j===i&&!ok)b.classList.add('bad');b.disabled=true});feedback.innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'Correct ✓':'Not quite'}</b><p>${q.explanation}</p><p><b>Key learning point:</b> ${q.learningPoint||q.explanation}</p>${!ok?`<p><b>Correct:</b> ${q.answer}</p>`:''}</div><button class="next" onclick="nextQ()">${SES.i===SES.items.length-1?'See results':'Next question'}</button>`}
function nextQ(){SES.i++;SES.done=false;if(SES.i>=SES.items.length)finish();else renderQ()}function finish(){clearInterval(TICK);let score=pc(SES.c,SES.items.length);if(SES.mock){S.mocks.push({date:new Date().toISOString(),score,correct:SES.c,total:SES.items.length});S.mocks=S.mocks.slice(-20);save()}quizbox.innerHTML=`<div class="card result"><small>${SES.mock?'MOCK RESULT':'SESSION COMPLETE'}</small><div class="score">${score}%</div><h2>${SES.mock?(score>=60?'PASS ✓':'Below pass mark'):'Nice work'}</h2><p>${SES.c} / ${SES.items.length} correct${SES.mock?' · pass mark 60%':''}</p><button class="primary" onclick="show('home')">Back to dashboard</button></div>`}function quitQuiz(){clearInterval(TICK);show('home')}
function learn(){topics.innerHTML=TOP.map(t=>{let tq=Q.filter(q=>q.topic===t),pts=[...new Set(tq.map(q=>q.learningPoint||q.explanation))].slice(0,6);return `<div class="topic"><div class="row"><div><b>${t}</b><div class="muted">${tq.length} exam-style questions</div></div><b>${st(t).a?mas(t)+'%':'—'}</b></div><div class="bar"><i style="width:${mas(t)}%"></i></div><div style="margin:12px 0"><small>KEY LEARNING POINTS</small><ul style="padding-left:20px;margin:8px 0">${pts.map(p=>`<li style="margin:7px 0">${p}</li>`).join('')}</ul></div><button onclick="startTopic('${t.replaceAll("'","\'")}')">Practice this topic</button></div>`}).join('')}
function showVault(){show('vault');let a=Object.values(S.wrong);vaultbox.innerHTML=a.length?`<button class="primary" onclick="retest()">Retest my mistakes</button>`+a.map(x=>`<div class="vaultitem"><small>${x.topic}</small><p><b>${x.question}</b></p><p class="muted">You chose: ${x.selected}</p><p><b>Correct:</b> ${x.answer}</p></div>`).join(''):`<div class="card"><h3>Vault empty 🎉</h3><p>No saved mistakes right now.</p></div>`}function retest(){let ids=new Set(Object.keys(S.wrong)),p=Q.filter(q=>ids.has(q.id));if(p.length)start('Wrong Answer Retest',sh(p).slice(0,20),false)}
function showFlash(){show('flash');FC=sh(Q).filter((q,i,a)=>a.findIndex(x=>x.concept===q.concept)===i).slice(0,25);FI=0;FLIP=false;renderFlash()}function renderFlash(){let q=FC[FI];flashbox.innerHTML=`<div class="qmeta">${q.topic} · ${FI+1}/${FC.length}</div><div class="flashcard" onclick="flipF()">${FLIP?`<div><b>${q.answer}</b><p class="muted"><b>Key learning point:</b> ${q.learningPoint||q.explanation}</p></div>`:`<div>${q.question}<p class="muted">Tap to reveal</p></div>`}</div>${FLIP?`<div class="flashbuttons"><button class="again" onclick="rateF(0)">Again</button><button class="hard" onclick="rateF(1)">Hard</button><button class="got" onclick="rateF(2)">Got it</button></div>`:''}`}function flipF(){FLIP=true;renderFlash()}function rateF(r){S.flash[FC[FI].concept]=r;save();FI=(FI+1)%FC.length;FLIP=false;renderFlash()}
function progress(){panswered.textContent=S.answered;pcorrect.textContent=S.correct;pmocks.textContent=S.mocks.length;mastery.innerHTML=TOP.map(t=>`<div class="masterrow"><div class="row"><b>${t}</b><span>${st(t).a?mas(t)+'%':'Not tested'} · ${st(t).a} Q</span></div><div class="bar"><i style="width:${mas(t)}%"></i></div></div>`).join('');mockhistory.innerHTML=S.mocks.length?S.mocks.slice().reverse().slice(0,8).map(m=>`<div class="weakrow"><div class="row"><span>${new Date(m.date).toLocaleDateString()}</span><b>${m.score}% · ${m.score>=60?'PASS':'REVIEW'}</b></div></div>`).join(''):'<p class="muted">No full mocks completed yet.</p>'}
function saveExamDate(){S.examDate=examdate.value;save();show('home')}function resetAll(){if(confirm('Reset all PrincePrep progress on this device?')){S=blank();save();show('home')}}home();
