/* PrincePrep v2.4 Interactive Learn */
let IL={module:null,step:0};
const ILQ={
core:['Which element sits at the centre of how PRINCE2 is established and managed?',['People','Processes','Practices'],'People','People are central: needs, capabilities, motivations and relationships affect how the method works.'],
principles:['A stage is forecast to exceed cost tolerance. Which principle tells the PM to escalate?',['Manage by stages','Manage by exception','Focus on products'],'Manage by exception','Tolerance defines delegated authority. A forecast breach is escalated.'],
people:['Which best describes change management?',['Moving the organization from current to target state','Controlling product versions','Authorizing work packages'],'Moving the organization from current to target state','Delivering an output is not enough: people must adopt the change to reach the target state.'],
businesscase:['Put the value chain in the best order.',['Output → Outcome → Benefit','Benefit → Output → Outcome','Outcome → Benefit → Output'],'Output → Outcome → Benefit','Outputs enable change; outcomes are results of change; benefits are measurable improvements arising from outcomes.'],
organizing:['Who is the single point of accountability and owns continued business justification?',['Project Manager','Executive','Senior User'],'Executive','The Executive chairs the Project Board and owns the business case and continued justification.'],
plans:['Which plan replaces a plan forecast to exceed tolerance, when requested?',['Team plan','Exception plan','Stage plan'],'Exception plan','An exception plan replaces the plan forecast to exceed tolerance when requested by the appropriate authority.'],
quality:['Which activity checks or tests a product against its quality specifications?',['Quality control','Quality assurance','Business justification'],'Quality control','Quality control tests or inspects products; quality assurance independently checks the system and standards.'],
risk:['A supplier might fail next month. What is it now?',['Issue','Risk','Off-specification'],'Risk','It is uncertain and future-facing. If it happens and requires consideration, it becomes an issue.'],
issues:['A product will not meet its quality specification. What type of issue is this?',['Request for change','Off-specification','Risk'],'Off-specification','An off-specification is a product that will not meet its quality specifications.'],
progress:['When does an exception exist?',['Only after tolerance is exceeded','When a tolerance breach is forecast','Whenever a checkpoint report is late'],'When a tolerance breach is forecast','PRINCE2 control is forward-looking: a forecast breach triggers escalation.'],
processes:['Which two processes interact repeatedly during a delivery stage?',['Controlling a Stage + Managing Product Delivery','Starting Up + Closing','Directing + Initiating'],'Controlling a Stage + Managing Product Delivery','The Project Manager controls the stage while teams accept, execute and deliver work packages.'],
performance:['Which performance target covers environmental, social and economic impact targets?',['Scope','Sustainability','Benefits'],'Sustainability','PRINCE2 7 explicitly includes sustainability as a project performance target.'],
products:['Which regular report flows from Team Manager to Project Manager?',['Highlight report','Checkpoint report','End stage report'],'Checkpoint report','Checkpoint reports are time-driven reports from Team Manager to Project Manager.']
};
const CONNECT={
risk:['UNCERTAINTY','CAUSE → EVENT → EFFECT','ASSESS EXPOSURE','CHOOSE RESPONSE','OWNER MONITORS'],
issues:['EVENT REQUIRES ATTENTION','CAPTURE','ASSESS','RECOMMEND','DECIDE','IMPLEMENT'],
progress:['PLAN','TOLERANCE','FORECAST','BREACH?','ESCALATE','DIRECTION / EXCEPTION PLAN'],
businesscase:['OUTPUT','CAPABILITY','OUTCOME','BENEFIT / DIS-BENEFIT','BUSINESS OBJECTIVE'],
processes:['STARTING UP','INITIATING','CONTROL STAGE ↔ PRODUCT DELIVERY','STAGE BOUNDARY','CLOSING'],
quality:['USER EXPECTATION','ACCEPTANCE CRITERIA','PRODUCT SPECIFICATION','CONTROL / TEST','ACCEPT'],
organizing:['BUSINESS → EXECUTIVE','USER → SENIOR USER','SUPPLIER → SENIOR SUPPLIER','BOARD DIRECTS','PM MANAGES','TEAM DELIVERS']
};
function learn(){
 let weights=LRN.weights||{};
 topics.innerHTML=`<div class="learn-intro"><small>INTERACTIVE LEARNING JOURNEY</small><h2>Learn it → connect it → prove it</h2><p>Short visual lessons built around the Foundation syllabus. Practices carry 60% of the exam, so they deserve the deepest attention.</p></div><div class="weight-card"><div class="weight-title">Exam map</div>${Object.entries(weights).map(([k,v])=>`<div class="weight-row"><span>${esc(k)}</span><div class="weightbar"><i style="width:${v}%"></i></div><b>${v}%</b></div>`).join('')}</div><div class="journey-grid">${(LRN.modules||[]).map((m,i)=>`<button class="journey-card" onclick="openLesson('${m.id}')"><span class="lesson-num">${String(i+1).padStart(2,'0')}</span><span class="lesson-icon">${m.icon}</span><b>${esc(m.title)}</b><small>${esc(m.accent)}</small><i>Start lesson →</i></button>`).join('')}</div>`;
}
function openLesson(id){IL={module:id,step:0};renderLesson()}
function renderLesson(){let m=(LRN.modules||[]).find(x=>x.id===IL.module);if(!m)return;let chain=CONNECT[m.id]||m.visual;topics.innerHTML=`<button class="lesson-back" onclick="learn()">← All lessons</button><div class="lesson-hero"><div class="lesson-icon big">${m.icon}</div><small>${esc(m.accent)}</small><h2>${esc(m.title)}</h2><div class="lesson-progress"><i style="width:${(IL.step+1)*25}%"></i></div><span>STEP ${IL.step+1} OF 4</span></div><div id="lessonbody"></div>`;let b=document.getElementById('lessonbody');if(IL.step===0)b.innerHTML=seeIt(m,chain);if(IL.step===1)b.innerHTML=understandIt(m);if(IL.step===2)b.innerHTML=connectIt(m,chain);if(IL.step===3)b.innerHTML=testIt(m)}
function seeIt(m,chain){return `<div class="lesson-panel"><small>1 · SEE IT</small><h3>Build the mental picture first</h3><div class="concept-map">${chain.map((x,i)=>`<div class="concept-node"><b>${esc(x)}</b>${i<chain.length-1?'<span>↓</span>':''}</div>`).join('')}</div><div class="memory"><b>MEMORY HOOK</b><span>${esc(m.memory)}</span></div><button class="primary" onclick="lessonNext()">I can picture it →</button></div>`}
function understandIt(m){return `<div class="lesson-panel"><small>2 · UNDERSTAND IT</small><h3>Tap each card to reveal the point</h3><div class="reveal-stack">${m.points.map((p,i)=>`<button onclick="this.classList.toggle('open')"><b>${i+1}</b><span class="reveal-prompt">Tap to reveal</span><span class="reveal-answer">${esc(p)}</span></button>`).join('')}</div><button class="primary" onclick="lessonNext()">Connect the dots →</button></div>`}
function connectIt(m,chain){return `<div class="lesson-panel"><small>3 · CONNECT IT</small><h3>How the idea moves through PRINCE2</h3><p class="muted">Follow the chain. Tap nodes as you explain the sequence to yourself.</p><div class="flow-map">${chain.map((x,i)=>`<button onclick="this.classList.toggle('lit')">${esc(x)}</button>${i<chain.length-1?'<span>→</span>':''}`).join('')}</div><div class="exam-lens"><b>EXAM LENS</b><p>Ask: <strong>who owns this, what triggers it, what information is produced, and what happens next?</strong></p></div><button class="primary" onclick="lessonNext()">Test me →</button></div>`}
function testIt(m){let q=ILQ[m.id]||[`Which statement best captures ${m.title}?`,[m.points[0],m.points[1]||m.memory,m.memory],m.points[0],m.points[0]];return `<div class="lesson-panel"><small>4 · PROVE IT</small><h3>${esc(q[0])}</h3><div class="lesson-options">${q[1].map((a,i)=>`<button onclick="lessonAnswer(this,${i})">${esc(a)}</button>`).join('')}</div><div id="lessonfeedback"></div></div>`}
function lessonNext(){IL.step=Math.min(3,IL.step+1);renderLesson();scrollTo(0,0)}
function lessonAnswer(btn,i){let m=(LRN.modules||[]).find(x=>x.id===IL.module),q=ILQ[m.id]||[``,[m.points[0],m.points[1]||m.memory,m.memory],m.points[0],m.points[0]],a=q[1][i],correct=q[2],why=q[3];document.querySelectorAll('.lesson-options button').forEach(x=>x.disabled=true);let ok=a===correct;btn.classList.add(ok?'good':'bad');if(!ok)[...document.querySelectorAll('.lesson-options button')].find(x=>x.textContent===correct)?.classList.add('good');lessonfeedback.innerHTML=`<div class="game-feedback ${ok?'good':'bad'}"><b>${ok?'Correct ✓':'Lock this one in'}</b><p>${esc(why)}</p></div><button class="primary" onclick="finishLesson()">Complete lesson</button>`}
function finishLesson(){let m=(LRN.modules||[]).find(x=>x.id===IL.module);topics.innerHTML=`<div class="lesson-complete"><div>✓</div><small>LESSON COMPLETE</small><h2>${esc(m.title)}</h2><p>${esc(m.memory)}</p><button class="primary" onclick="learn()">Choose next lesson</button><button class="secondary wide" onclick="showFlash()">Review flashcards</button></div>`;mark()}
